#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TTCM")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertchiTietHDN(chiTietHDN instance);
    partial void UpdatechiTietHDN(chiTietHDN instance);
    partial void DeletechiTietHDN(chiTietHDN instance);
    partial void InsertsanPham(sanPham instance);
    partial void UpdatesanPham(sanPham instance);
    partial void DeletesanPham(sanPham instance);
    partial void InsertchiTietHDX(chiTietHDX instance);
    partial void UpdatechiTietHDX(chiTietHDX instance);
    partial void DeletechiTietHDX(chiTietHDX instance);
    partial void InsertchiTietSP(chiTietSP instance);
    partial void UpdatechiTietSP(chiTietSP instance);
    partial void DeletechiTietSP(chiTietSP instance);
    partial void InsertcongViec(congViec instance);
    partial void UpdatecongViec(congViec instance);
    partial void DeletecongViec(congViec instance);
    partial void InserthoadDonNhap(hoadDonNhap instance);
    partial void UpdatehoadDonNhap(hoadDonNhap instance);
    partial void DeletehoadDonNhap(hoadDonNhap instance);
    partial void InserthoadDonXuat(hoadDonXuat instance);
    partial void UpdatehoadDonXuat(hoadDonXuat instance);
    partial void DeletehoadDonXuat(hoadDonXuat instance);
    partial void InsertkhachHang(khachHang instance);
    partial void UpdatekhachHang(khachHang instance);
    partial void DeletekhachHang(khachHang instance);
    partial void InsertnhaCungCap(nhaCungCap instance);
    partial void UpdatenhaCungCap(nhaCungCap instance);
    partial void DeletenhaCungCap(nhaCungCap instance);
    partial void InsertnhanVien(nhanVien instance);
    partial void UpdatenhanVien(nhanVien instance);
    partial void DeletenhanVien(nhanVien instance);
    partial void InsertnhomSP(nhomSP instance);
    partial void UpdatenhomSP(nhomSP instance);
    partial void DeletenhomSP(nhomSP instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WindowsFormsApp1.Properties.Settings.Default.TTCMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<chiTietHDN> chiTietHDNs
		{
			get
			{
				return this.GetTable<chiTietHDN>();
			}
		}
		
		public System.Data.Linq.Table<sanPham> sanPhams
		{
			get
			{
				return this.GetTable<sanPham>();
			}
		}
		
		public System.Data.Linq.Table<chiTietHDX> chiTietHDXes
		{
			get
			{
				return this.GetTable<chiTietHDX>();
			}
		}
		
		public System.Data.Linq.Table<chiTietSP> chiTietSPs
		{
			get
			{
				return this.GetTable<chiTietSP>();
			}
		}
		
		public System.Data.Linq.Table<congViec> congViecs
		{
			get
			{
				return this.GetTable<congViec>();
			}
		}
		
		public System.Data.Linq.Table<hoadDonNhap> hoadDonNhaps
		{
			get
			{
				return this.GetTable<hoadDonNhap>();
			}
		}
		
		public System.Data.Linq.Table<hoadDonXuat> hoadDonXuats
		{
			get
			{
				return this.GetTable<hoadDonXuat>();
			}
		}
		
		public System.Data.Linq.Table<khachHang> khachHangs
		{
			get
			{
				return this.GetTable<khachHang>();
			}
		}
		
		public System.Data.Linq.Table<nhaCungCap> nhaCungCaps
		{
			get
			{
				return this.GetTable<nhaCungCap>();
			}
		}
		
		public System.Data.Linq.Table<nhanVien> nhanViens
		{
			get
			{
				return this.GetTable<nhanVien>();
			}
		}
		
		public System.Data.Linq.Table<nhomSP> nhomSPs
		{
			get
			{
				return this.GetTable<nhomSP>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addSP")]
		public int addSP([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maSP, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenSP, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> gia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Image")] System.Data.Linq.Binary anh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soLuong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string thongSo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maLoai)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSP, tenSP, gia, anh, soLuong, thongSo, maLoai);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.select_SP")]
		public ISingleResult<select_SPResult> select_SP()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<select_SPResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateSP")]
		public int updateSP([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maSP, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenSP, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> gia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Image")] System.Data.Linq.Binary anh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maLoai)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSP, tenSP, gia, anh, maLoai);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deleteSP")]
		public int deleteSP([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maSP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSP);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chiTietHDN")]
	public partial class chiTietHDN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHDN;
		
		private string _maSP;
		
		private System.Nullable<double> _donGia;
		
		private System.Nullable<int> _soLuong;
		
		private System.Nullable<double> _thanhTien;
		
		private EntityRef<sanPham> _sanPham;
		
		private EntityRef<hoadDonNhap> _hoadDonNhap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDNChanging(string value);
    partial void OnmaHDNChanged();
    partial void OnmaSPChanging(string value);
    partial void OnmaSPChanged();
    partial void OndonGiaChanging(System.Nullable<double> value);
    partial void OndonGiaChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OnthanhTienChanging(System.Nullable<double> value);
    partial void OnthanhTienChanged();
    #endregion
		
		public chiTietHDN()
		{
			this._sanPham = default(EntityRef<sanPham>);
			this._hoadDonNhap = default(EntityRef<hoadDonNhap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHDN", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHDN
		{
			get
			{
				return this._maHDN;
			}
			set
			{
				if ((this._maHDN != value))
				{
					if (this._hoadDonNhap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHDNChanging(value);
					this.SendPropertyChanging();
					this._maHDN = value;
					this.SendPropertyChanged("maHDN");
					this.OnmaHDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSP", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maSP
		{
			get
			{
				return this._maSP;
			}
			set
			{
				if ((this._maSP != value))
				{
					if (this._sanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaSPChanging(value);
					this.SendPropertyChanging();
					this._maSP = value;
					this.SendPropertyChanged("maSP");
					this.OnmaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donGia", DbType="Float")]
		public System.Nullable<double> donGia
		{
			get
			{
				return this._donGia;
			}
			set
			{
				if ((this._donGia != value))
				{
					this.OndonGiaChanging(value);
					this.SendPropertyChanging();
					this._donGia = value;
					this.SendPropertyChanged("donGia");
					this.OndonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhTien", DbType="Float")]
		public System.Nullable<double> thanhTien
		{
			get
			{
				return this._thanhTien;
			}
			set
			{
				if ((this._thanhTien != value))
				{
					this.OnthanhTienChanging(value);
					this.SendPropertyChanging();
					this._thanhTien = value;
					this.SendPropertyChanged("thanhTien");
					this.OnthanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanPham_chiTietHDN", Storage="_sanPham", ThisKey="maSP", OtherKey="maSP", IsForeignKey=true)]
		public sanPham sanPham
		{
			get
			{
				return this._sanPham.Entity;
			}
			set
			{
				sanPham previousValue = this._sanPham.Entity;
				if (((previousValue != value) 
							|| (this._sanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanPham.Entity = null;
						previousValue.chiTietHDNs.Remove(this);
					}
					this._sanPham.Entity = value;
					if ((value != null))
					{
						value.chiTietHDNs.Add(this);
						this._maSP = value.maSP;
					}
					else
					{
						this._maSP = default(string);
					}
					this.SendPropertyChanged("sanPham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoadDonNhap_chiTietHDN", Storage="_hoadDonNhap", ThisKey="maHDN", OtherKey="maHDN", IsForeignKey=true)]
		public hoadDonNhap hoadDonNhap
		{
			get
			{
				return this._hoadDonNhap.Entity;
			}
			set
			{
				hoadDonNhap previousValue = this._hoadDonNhap.Entity;
				if (((previousValue != value) 
							|| (this._hoadDonNhap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hoadDonNhap.Entity = null;
						previousValue.chiTietHDNs.Remove(this);
					}
					this._hoadDonNhap.Entity = value;
					if ((value != null))
					{
						value.chiTietHDNs.Add(this);
						this._maHDN = value.maHDN;
					}
					else
					{
						this._maHDN = default(string);
					}
					this.SendPropertyChanged("hoadDonNhap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sanPham")]
	public partial class sanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maSP;
		
		private string _tenSP;
		
		private System.Nullable<double> _gia;
		
		private System.Data.Linq.Binary _anh;
		
		private System.Nullable<int> _soLuong;
		
		private string _thongSo;
		
		private string _maLoai;
		
		private EntitySet<chiTietHDN> _chiTietHDNs;
		
		private EntitySet<chiTietHDX> _chiTietHDXes;
		
		private EntitySet<chiTietSP> _chiTietSPs;
		
		private EntityRef<nhomSP> _nhomSP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaSPChanging(string value);
    partial void OnmaSPChanged();
    partial void OntenSPChanging(string value);
    partial void OntenSPChanged();
    partial void OngiaChanging(System.Nullable<double> value);
    partial void OngiaChanged();
    partial void OnanhChanging(System.Data.Linq.Binary value);
    partial void OnanhChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OnthongSoChanging(string value);
    partial void OnthongSoChanged();
    partial void OnmaLoaiChanging(string value);
    partial void OnmaLoaiChanged();
    #endregion
		
		public sanPham()
		{
			this._chiTietHDNs = new EntitySet<chiTietHDN>(new Action<chiTietHDN>(this.attach_chiTietHDNs), new Action<chiTietHDN>(this.detach_chiTietHDNs));
			this._chiTietHDXes = new EntitySet<chiTietHDX>(new Action<chiTietHDX>(this.attach_chiTietHDXes), new Action<chiTietHDX>(this.detach_chiTietHDXes));
			this._chiTietSPs = new EntitySet<chiTietSP>(new Action<chiTietSP>(this.attach_chiTietSPs), new Action<chiTietSP>(this.detach_chiTietSPs));
			this._nhomSP = default(EntityRef<nhomSP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSP", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maSP
		{
			get
			{
				return this._maSP;
			}
			set
			{
				if ((this._maSP != value))
				{
					this.OnmaSPChanging(value);
					this.SendPropertyChanging();
					this._maSP = value;
					this.SendPropertyChanged("maSP");
					this.OnmaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenSP", DbType="NVarChar(50)")]
		public string tenSP
		{
			get
			{
				return this._tenSP;
			}
			set
			{
				if ((this._tenSP != value))
				{
					this.OntenSPChanging(value);
					this.SendPropertyChanging();
					this._tenSP = value;
					this.SendPropertyChanged("tenSP");
					this.OntenSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Float")]
		public System.Nullable<double> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anh", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary anh
		{
			get
			{
				return this._anh;
			}
			set
			{
				if ((this._anh != value))
				{
					this.OnanhChanging(value);
					this.SendPropertyChanging();
					this._anh = value;
					this.SendPropertyChanged("anh");
					this.OnanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thongSo", DbType="NVarChar(50)")]
		public string thongSo
		{
			get
			{
				return this._thongSo;
			}
			set
			{
				if ((this._thongSo != value))
				{
					this.OnthongSoChanging(value);
					this.SendPropertyChanging();
					this._thongSo = value;
					this.SendPropertyChanged("thongSo");
					this.OnthongSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", DbType="NVarChar(50)")]
		public string maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					if (this._nhomSP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLoaiChanging(value);
					this.SendPropertyChanging();
					this._maLoai = value;
					this.SendPropertyChanged("maLoai");
					this.OnmaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanPham_chiTietHDN", Storage="_chiTietHDNs", ThisKey="maSP", OtherKey="maSP")]
		public EntitySet<chiTietHDN> chiTietHDNs
		{
			get
			{
				return this._chiTietHDNs;
			}
			set
			{
				this._chiTietHDNs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanPham_chiTietHDX", Storage="_chiTietHDXes", ThisKey="maSP", OtherKey="maSP")]
		public EntitySet<chiTietHDX> chiTietHDXes
		{
			get
			{
				return this._chiTietHDXes;
			}
			set
			{
				this._chiTietHDXes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanPham_chiTietSP", Storage="_chiTietSPs", ThisKey="maSP", OtherKey="maSP")]
		public EntitySet<chiTietSP> chiTietSPs
		{
			get
			{
				return this._chiTietSPs;
			}
			set
			{
				this._chiTietSPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhomSP_sanPham", Storage="_nhomSP", ThisKey="maLoai", OtherKey="maLoai", IsForeignKey=true)]
		public nhomSP nhomSP
		{
			get
			{
				return this._nhomSP.Entity;
			}
			set
			{
				nhomSP previousValue = this._nhomSP.Entity;
				if (((previousValue != value) 
							|| (this._nhomSP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhomSP.Entity = null;
						previousValue.sanPhams.Remove(this);
					}
					this._nhomSP.Entity = value;
					if ((value != null))
					{
						value.sanPhams.Add(this);
						this._maLoai = value.maLoai;
					}
					else
					{
						this._maLoai = default(string);
					}
					this.SendPropertyChanged("nhomSP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chiTietHDNs(chiTietHDN entity)
		{
			this.SendPropertyChanging();
			entity.sanPham = this;
		}
		
		private void detach_chiTietHDNs(chiTietHDN entity)
		{
			this.SendPropertyChanging();
			entity.sanPham = null;
		}
		
		private void attach_chiTietHDXes(chiTietHDX entity)
		{
			this.SendPropertyChanging();
			entity.sanPham = this;
		}
		
		private void detach_chiTietHDXes(chiTietHDX entity)
		{
			this.SendPropertyChanging();
			entity.sanPham = null;
		}
		
		private void attach_chiTietSPs(chiTietSP entity)
		{
			this.SendPropertyChanging();
			entity.sanPham = this;
		}
		
		private void detach_chiTietSPs(chiTietSP entity)
		{
			this.SendPropertyChanging();
			entity.sanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chiTietHDX")]
	public partial class chiTietHDX : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHDX;
		
		private string _maSP;
		
		private System.Nullable<double> _donGia;
		
		private System.Nullable<int> _soLuong;
		
		private System.Nullable<double> _thanhTien;
		
		private EntityRef<sanPham> _sanPham;
		
		private EntityRef<hoadDonXuat> _hoadDonXuat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDXChanging(string value);
    partial void OnmaHDXChanged();
    partial void OnmaSPChanging(string value);
    partial void OnmaSPChanged();
    partial void OndonGiaChanging(System.Nullable<double> value);
    partial void OndonGiaChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OnthanhTienChanging(System.Nullable<double> value);
    partial void OnthanhTienChanged();
    #endregion
		
		public chiTietHDX()
		{
			this._sanPham = default(EntityRef<sanPham>);
			this._hoadDonXuat = default(EntityRef<hoadDonXuat>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHDX", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHDX
		{
			get
			{
				return this._maHDX;
			}
			set
			{
				if ((this._maHDX != value))
				{
					if (this._hoadDonXuat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHDXChanging(value);
					this.SendPropertyChanging();
					this._maHDX = value;
					this.SendPropertyChanged("maHDX");
					this.OnmaHDXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSP", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maSP
		{
			get
			{
				return this._maSP;
			}
			set
			{
				if ((this._maSP != value))
				{
					if (this._sanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaSPChanging(value);
					this.SendPropertyChanging();
					this._maSP = value;
					this.SendPropertyChanged("maSP");
					this.OnmaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donGia", DbType="Float")]
		public System.Nullable<double> donGia
		{
			get
			{
				return this._donGia;
			}
			set
			{
				if ((this._donGia != value))
				{
					this.OndonGiaChanging(value);
					this.SendPropertyChanging();
					this._donGia = value;
					this.SendPropertyChanged("donGia");
					this.OndonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhTien", DbType="Float")]
		public System.Nullable<double> thanhTien
		{
			get
			{
				return this._thanhTien;
			}
			set
			{
				if ((this._thanhTien != value))
				{
					this.OnthanhTienChanging(value);
					this.SendPropertyChanging();
					this._thanhTien = value;
					this.SendPropertyChanged("thanhTien");
					this.OnthanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanPham_chiTietHDX", Storage="_sanPham", ThisKey="maSP", OtherKey="maSP", IsForeignKey=true)]
		public sanPham sanPham
		{
			get
			{
				return this._sanPham.Entity;
			}
			set
			{
				sanPham previousValue = this._sanPham.Entity;
				if (((previousValue != value) 
							|| (this._sanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanPham.Entity = null;
						previousValue.chiTietHDXes.Remove(this);
					}
					this._sanPham.Entity = value;
					if ((value != null))
					{
						value.chiTietHDXes.Add(this);
						this._maSP = value.maSP;
					}
					else
					{
						this._maSP = default(string);
					}
					this.SendPropertyChanged("sanPham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoadDonXuat_chiTietHDX", Storage="_hoadDonXuat", ThisKey="maHDX", OtherKey="maHDX", IsForeignKey=true)]
		public hoadDonXuat hoadDonXuat
		{
			get
			{
				return this._hoadDonXuat.Entity;
			}
			set
			{
				hoadDonXuat previousValue = this._hoadDonXuat.Entity;
				if (((previousValue != value) 
							|| (this._hoadDonXuat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hoadDonXuat.Entity = null;
						previousValue.chiTietHDXes.Remove(this);
					}
					this._hoadDonXuat.Entity = value;
					if ((value != null))
					{
						value.chiTietHDXes.Add(this);
						this._maHDX = value.maHDX;
					}
					else
					{
						this._maHDX = default(string);
					}
					this.SendPropertyChanged("hoadDonXuat");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chiTietSP")]
	public partial class chiTietSP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maSP;
		
		private string _soSerial;
		
		private string _color;
		
		private EntityRef<sanPham> _sanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaSPChanging(string value);
    partial void OnmaSPChanged();
    partial void OnsoSerialChanging(string value);
    partial void OnsoSerialChanged();
    partial void OncolorChanging(string value);
    partial void OncolorChanged();
    #endregion
		
		public chiTietSP()
		{
			this._sanPham = default(EntityRef<sanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSP", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maSP
		{
			get
			{
				return this._maSP;
			}
			set
			{
				if ((this._maSP != value))
				{
					if (this._sanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaSPChanging(value);
					this.SendPropertyChanging();
					this._maSP = value;
					this.SendPropertyChanged("maSP");
					this.OnmaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soSerial", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string soSerial
		{
			get
			{
				return this._soSerial;
			}
			set
			{
				if ((this._soSerial != value))
				{
					this.OnsoSerialChanging(value);
					this.SendPropertyChanging();
					this._soSerial = value;
					this.SendPropertyChanged("soSerial");
					this.OnsoSerialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="NVarChar(50)")]
		public string color
		{
			get
			{
				return this._color;
			}
			set
			{
				if ((this._color != value))
				{
					this.OncolorChanging(value);
					this.SendPropertyChanging();
					this._color = value;
					this.SendPropertyChanged("color");
					this.OncolorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanPham_chiTietSP", Storage="_sanPham", ThisKey="maSP", OtherKey="maSP", IsForeignKey=true)]
		public sanPham sanPham
		{
			get
			{
				return this._sanPham.Entity;
			}
			set
			{
				sanPham previousValue = this._sanPham.Entity;
				if (((previousValue != value) 
							|| (this._sanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanPham.Entity = null;
						previousValue.chiTietSPs.Remove(this);
					}
					this._sanPham.Entity = value;
					if ((value != null))
					{
						value.chiTietSPs.Add(this);
						this._maSP = value.maSP;
					}
					else
					{
						this._maSP = default(string);
					}
					this.SendPropertyChanged("sanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.congViec")]
	public partial class congViec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maCV;
		
		private string _tenCV;
		
		private System.Nullable<double> _bacLuong;
		
		private EntitySet<nhanVien> _nhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCVChanging(string value);
    partial void OnmaCVChanged();
    partial void OntenCVChanging(string value);
    partial void OntenCVChanged();
    partial void OnbacLuongChanging(System.Nullable<double> value);
    partial void OnbacLuongChanged();
    #endregion
		
		public congViec()
		{
			this._nhanViens = new EntitySet<nhanVien>(new Action<nhanVien>(this.attach_nhanViens), new Action<nhanVien>(this.detach_nhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCV", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maCV
		{
			get
			{
				return this._maCV;
			}
			set
			{
				if ((this._maCV != value))
				{
					this.OnmaCVChanging(value);
					this.SendPropertyChanging();
					this._maCV = value;
					this.SendPropertyChanged("maCV");
					this.OnmaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCV", DbType="NVarChar(50)")]
		public string tenCV
		{
			get
			{
				return this._tenCV;
			}
			set
			{
				if ((this._tenCV != value))
				{
					this.OntenCVChanging(value);
					this.SendPropertyChanging();
					this._tenCV = value;
					this.SendPropertyChanged("tenCV");
					this.OntenCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bacLuong", DbType="Float")]
		public System.Nullable<double> bacLuong
		{
			get
			{
				return this._bacLuong;
			}
			set
			{
				if ((this._bacLuong != value))
				{
					this.OnbacLuongChanging(value);
					this.SendPropertyChanging();
					this._bacLuong = value;
					this.SendPropertyChanged("bacLuong");
					this.OnbacLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="congViec_nhanVien", Storage="_nhanViens", ThisKey="maCV", OtherKey="maCV")]
		public EntitySet<nhanVien> nhanViens
		{
			get
			{
				return this._nhanViens;
			}
			set
			{
				this._nhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nhanViens(nhanVien entity)
		{
			this.SendPropertyChanging();
			entity.congViec = this;
		}
		
		private void detach_nhanViens(nhanVien entity)
		{
			this.SendPropertyChanging();
			entity.congViec = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hoadDonNhap")]
	public partial class hoadDonNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHDN;
		
		private string _maNV;
		
		private string _maNCC;
		
		private System.Nullable<System.DateTime> _ngayNhap;
		
		private System.Nullable<double> _tongTien;
		
		private string _trangThai;
		
		private EntitySet<chiTietHDN> _chiTietHDNs;
		
		private EntityRef<nhaCungCap> _nhaCungCap;
		
		private EntityRef<nhanVien> _nhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDNChanging(string value);
    partial void OnmaHDNChanged();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OnmaNCCChanging(string value);
    partial void OnmaNCCChanged();
    partial void OnngayNhapChanging(System.Nullable<System.DateTime> value);
    partial void OnngayNhapChanged();
    partial void OntongTienChanging(System.Nullable<double> value);
    partial void OntongTienChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    #endregion
		
		public hoadDonNhap()
		{
			this._chiTietHDNs = new EntitySet<chiTietHDN>(new Action<chiTietHDN>(this.attach_chiTietHDNs), new Action<chiTietHDN>(this.detach_chiTietHDNs));
			this._nhaCungCap = default(EntityRef<nhaCungCap>);
			this._nhanVien = default(EntityRef<nhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHDN", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHDN
		{
			get
			{
				return this._maHDN;
			}
			set
			{
				if ((this._maHDN != value))
				{
					this.OnmaHDNChanging(value);
					this.SendPropertyChanging();
					this._maHDN = value;
					this.SendPropertyChanged("maHDN");
					this.OnmaHDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="NVarChar(50)")]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._nhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNCC", DbType="NVarChar(50)")]
		public string maNCC
		{
			get
			{
				return this._maNCC;
			}
			set
			{
				if ((this._maNCC != value))
				{
					if (this._nhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNCCChanging(value);
					this.SendPropertyChanging();
					this._maNCC = value;
					this.SendPropertyChanged("maNCC");
					this.OnmaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayNhap", DbType="Date")]
		public System.Nullable<System.DateTime> ngayNhap
		{
			get
			{
				return this._ngayNhap;
			}
			set
			{
				if ((this._ngayNhap != value))
				{
					this.OnngayNhapChanging(value);
					this.SendPropertyChanging();
					this._ngayNhap = value;
					this.SendPropertyChanged("ngayNhap");
					this.OnngayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongTien", DbType="Float")]
		public System.Nullable<double> tongTien
		{
			get
			{
				return this._tongTien;
			}
			set
			{
				if ((this._tongTien != value))
				{
					this.OntongTienChanging(value);
					this.SendPropertyChanging();
					this._tongTien = value;
					this.SendPropertyChanged("tongTien");
					this.OntongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NVarChar(50)")]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoadDonNhap_chiTietHDN", Storage="_chiTietHDNs", ThisKey="maHDN", OtherKey="maHDN")]
		public EntitySet<chiTietHDN> chiTietHDNs
		{
			get
			{
				return this._chiTietHDNs;
			}
			set
			{
				this._chiTietHDNs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhaCungCap_hoadDonNhap", Storage="_nhaCungCap", ThisKey="maNCC", OtherKey="maNCC", IsForeignKey=true)]
		public nhaCungCap nhaCungCap
		{
			get
			{
				return this._nhaCungCap.Entity;
			}
			set
			{
				nhaCungCap previousValue = this._nhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._nhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhaCungCap.Entity = null;
						previousValue.hoadDonNhaps.Remove(this);
					}
					this._nhaCungCap.Entity = value;
					if ((value != null))
					{
						value.hoadDonNhaps.Add(this);
						this._maNCC = value.maNCC;
					}
					else
					{
						this._maNCC = default(string);
					}
					this.SendPropertyChanged("nhaCungCap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanVien_hoadDonNhap", Storage="_nhanVien", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true)]
		public nhanVien nhanVien
		{
			get
			{
				return this._nhanVien.Entity;
			}
			set
			{
				nhanVien previousValue = this._nhanVien.Entity;
				if (((previousValue != value) 
							|| (this._nhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanVien.Entity = null;
						previousValue.hoadDonNhaps.Remove(this);
					}
					this._nhanVien.Entity = value;
					if ((value != null))
					{
						value.hoadDonNhaps.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(string);
					}
					this.SendPropertyChanged("nhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chiTietHDNs(chiTietHDN entity)
		{
			this.SendPropertyChanging();
			entity.hoadDonNhap = this;
		}
		
		private void detach_chiTietHDNs(chiTietHDN entity)
		{
			this.SendPropertyChanging();
			entity.hoadDonNhap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hoadDonXuat")]
	public partial class hoadDonXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHDX;
		
		private string _maNV;
		
		private string _maKH;
		
		private System.Nullable<System.DateTime> _ngayBan;
		
		private System.Nullable<double> _tongTien;
		
		private string _trangThai;
		
		private EntitySet<chiTietHDX> _chiTietHDXes;
		
		private EntityRef<khachHang> _khachHang;
		
		private EntityRef<nhanVien> _nhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDXChanging(string value);
    partial void OnmaHDXChanged();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    partial void OnngayBanChanging(System.Nullable<System.DateTime> value);
    partial void OnngayBanChanged();
    partial void OntongTienChanging(System.Nullable<double> value);
    partial void OntongTienChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    #endregion
		
		public hoadDonXuat()
		{
			this._chiTietHDXes = new EntitySet<chiTietHDX>(new Action<chiTietHDX>(this.attach_chiTietHDXes), new Action<chiTietHDX>(this.detach_chiTietHDXes));
			this._khachHang = default(EntityRef<khachHang>);
			this._nhanVien = default(EntityRef<nhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHDX", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHDX
		{
			get
			{
				return this._maHDX;
			}
			set
			{
				if ((this._maHDX != value))
				{
					this.OnmaHDXChanging(value);
					this.SendPropertyChanging();
					this._maHDX = value;
					this.SendPropertyChanged("maHDX");
					this.OnmaHDXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="NVarChar(50)")]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._nhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="NVarChar(50)")]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					if (this._khachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayBan", DbType="Date")]
		public System.Nullable<System.DateTime> ngayBan
		{
			get
			{
				return this._ngayBan;
			}
			set
			{
				if ((this._ngayBan != value))
				{
					this.OnngayBanChanging(value);
					this.SendPropertyChanging();
					this._ngayBan = value;
					this.SendPropertyChanged("ngayBan");
					this.OnngayBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongTien", DbType="Float")]
		public System.Nullable<double> tongTien
		{
			get
			{
				return this._tongTien;
			}
			set
			{
				if ((this._tongTien != value))
				{
					this.OntongTienChanging(value);
					this.SendPropertyChanging();
					this._tongTien = value;
					this.SendPropertyChanged("tongTien");
					this.OntongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NVarChar(50)")]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoadDonXuat_chiTietHDX", Storage="_chiTietHDXes", ThisKey="maHDX", OtherKey="maHDX")]
		public EntitySet<chiTietHDX> chiTietHDXes
		{
			get
			{
				return this._chiTietHDXes;
			}
			set
			{
				this._chiTietHDXes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachHang_hoadDonXuat", Storage="_khachHang", ThisKey="maKH", OtherKey="maKH", IsForeignKey=true)]
		public khachHang khachHang
		{
			get
			{
				return this._khachHang.Entity;
			}
			set
			{
				khachHang previousValue = this._khachHang.Entity;
				if (((previousValue != value) 
							|| (this._khachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachHang.Entity = null;
						previousValue.hoadDonXuats.Remove(this);
					}
					this._khachHang.Entity = value;
					if ((value != null))
					{
						value.hoadDonXuats.Add(this);
						this._maKH = value.maKH;
					}
					else
					{
						this._maKH = default(string);
					}
					this.SendPropertyChanged("khachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanVien_hoadDonXuat", Storage="_nhanVien", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true)]
		public nhanVien nhanVien
		{
			get
			{
				return this._nhanVien.Entity;
			}
			set
			{
				nhanVien previousValue = this._nhanVien.Entity;
				if (((previousValue != value) 
							|| (this._nhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanVien.Entity = null;
						previousValue.hoadDonXuats.Remove(this);
					}
					this._nhanVien.Entity = value;
					if ((value != null))
					{
						value.hoadDonXuats.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(string);
					}
					this.SendPropertyChanged("nhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chiTietHDXes(chiTietHDX entity)
		{
			this.SendPropertyChanging();
			entity.hoadDonXuat = this;
		}
		
		private void detach_chiTietHDXes(chiTietHDX entity)
		{
			this.SendPropertyChanging();
			entity.hoadDonXuat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachHang")]
	public partial class khachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKH;
		
		private string _tenKH;
		
		private string _email;
		
		private string _diaChi;
		
		private string _sdt;
		
		private EntitySet<hoadDonXuat> _hoadDonXuats;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    partial void OntenKHChanging(string value);
    partial void OntenKHChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    #endregion
		
		public khachHang()
		{
			this._hoadDonXuats = new EntitySet<hoadDonXuat>(new Action<hoadDonXuat>(this.attach_hoadDonXuats), new Action<hoadDonXuat>(this.detach_hoadDonXuats));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKH", DbType="NVarChar(50)")]
		public string tenKH
		{
			get
			{
				return this._tenKH;
			}
			set
			{
				if ((this._tenKH != value))
				{
					this.OntenKHChanging(value);
					this.SendPropertyChanging();
					this._tenKH = value;
					this.SendPropertyChanged("tenKH");
					this.OntenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(50)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="NVarChar(50)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachHang_hoadDonXuat", Storage="_hoadDonXuats", ThisKey="maKH", OtherKey="maKH")]
		public EntitySet<hoadDonXuat> hoadDonXuats
		{
			get
			{
				return this._hoadDonXuats;
			}
			set
			{
				this._hoadDonXuats.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoadDonXuats(hoadDonXuat entity)
		{
			this.SendPropertyChanging();
			entity.khachHang = this;
		}
		
		private void detach_hoadDonXuats(hoadDonXuat entity)
		{
			this.SendPropertyChanging();
			entity.khachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhaCungCap")]
	public partial class nhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNCC;
		
		private string _tenNCC;
		
		private string _email;
		
		private string _diaChi;
		
		private string _sdt;
		
		private EntitySet<hoadDonNhap> _hoadDonNhaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNCCChanging(string value);
    partial void OnmaNCCChanged();
    partial void OntenNCCChanging(string value);
    partial void OntenNCCChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    #endregion
		
		public nhaCungCap()
		{
			this._hoadDonNhaps = new EntitySet<hoadDonNhap>(new Action<hoadDonNhap>(this.attach_hoadDonNhaps), new Action<hoadDonNhap>(this.detach_hoadDonNhaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNCC", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNCC
		{
			get
			{
				return this._maNCC;
			}
			set
			{
				if ((this._maNCC != value))
				{
					this.OnmaNCCChanging(value);
					this.SendPropertyChanging();
					this._maNCC = value;
					this.SendPropertyChanged("maNCC");
					this.OnmaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNCC", DbType="NVarChar(50)")]
		public string tenNCC
		{
			get
			{
				return this._tenNCC;
			}
			set
			{
				if ((this._tenNCC != value))
				{
					this.OntenNCCChanging(value);
					this.SendPropertyChanging();
					this._tenNCC = value;
					this.SendPropertyChanged("tenNCC");
					this.OntenNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(50)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="NVarChar(50)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhaCungCap_hoadDonNhap", Storage="_hoadDonNhaps", ThisKey="maNCC", OtherKey="maNCC")]
		public EntitySet<hoadDonNhap> hoadDonNhaps
		{
			get
			{
				return this._hoadDonNhaps;
			}
			set
			{
				this._hoadDonNhaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoadDonNhaps(hoadDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.nhaCungCap = this;
		}
		
		private void detach_hoadDonNhaps(hoadDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.nhaCungCap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhanVien")]
	public partial class nhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNV;
		
		private string _tenNV;
		
		private string _email;
		
		private string _diaChi;
		
		private string _sdt;
		
		private string _passWords;
		
		private string _maCV;
		
		private EntitySet<hoadDonNhap> _hoadDonNhaps;
		
		private EntitySet<hoadDonXuat> _hoadDonXuats;
		
		private EntityRef<congViec> _congViec;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OntenNVChanging(string value);
    partial void OntenNVChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OnpassWordsChanging(string value);
    partial void OnpassWordsChanged();
    partial void OnmaCVChanging(string value);
    partial void OnmaCVChanged();
    #endregion
		
		public nhanVien()
		{
			this._hoadDonNhaps = new EntitySet<hoadDonNhap>(new Action<hoadDonNhap>(this.attach_hoadDonNhaps), new Action<hoadDonNhap>(this.detach_hoadDonNhaps));
			this._hoadDonXuats = new EntitySet<hoadDonXuat>(new Action<hoadDonXuat>(this.attach_hoadDonXuats), new Action<hoadDonXuat>(this.detach_hoadDonXuats));
			this._congViec = default(EntityRef<congViec>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNV", DbType="NVarChar(50)")]
		public string tenNV
		{
			get
			{
				return this._tenNV;
			}
			set
			{
				if ((this._tenNV != value))
				{
					this.OntenNVChanging(value);
					this.SendPropertyChanging();
					this._tenNV = value;
					this.SendPropertyChanged("tenNV");
					this.OntenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(50)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="NVarChar(50)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passWords", DbType="NVarChar(50)")]
		public string passWords
		{
			get
			{
				return this._passWords;
			}
			set
			{
				if ((this._passWords != value))
				{
					this.OnpassWordsChanging(value);
					this.SendPropertyChanging();
					this._passWords = value;
					this.SendPropertyChanged("passWords");
					this.OnpassWordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCV", DbType="NVarChar(50)")]
		public string maCV
		{
			get
			{
				return this._maCV;
			}
			set
			{
				if ((this._maCV != value))
				{
					if (this._congViec.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaCVChanging(value);
					this.SendPropertyChanging();
					this._maCV = value;
					this.SendPropertyChanged("maCV");
					this.OnmaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanVien_hoadDonNhap", Storage="_hoadDonNhaps", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<hoadDonNhap> hoadDonNhaps
		{
			get
			{
				return this._hoadDonNhaps;
			}
			set
			{
				this._hoadDonNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanVien_hoadDonXuat", Storage="_hoadDonXuats", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<hoadDonXuat> hoadDonXuats
		{
			get
			{
				return this._hoadDonXuats;
			}
			set
			{
				this._hoadDonXuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="congViec_nhanVien", Storage="_congViec", ThisKey="maCV", OtherKey="maCV", IsForeignKey=true)]
		public congViec congViec
		{
			get
			{
				return this._congViec.Entity;
			}
			set
			{
				congViec previousValue = this._congViec.Entity;
				if (((previousValue != value) 
							|| (this._congViec.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._congViec.Entity = null;
						previousValue.nhanViens.Remove(this);
					}
					this._congViec.Entity = value;
					if ((value != null))
					{
						value.nhanViens.Add(this);
						this._maCV = value.maCV;
					}
					else
					{
						this._maCV = default(string);
					}
					this.SendPropertyChanged("congViec");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoadDonNhaps(hoadDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.nhanVien = this;
		}
		
		private void detach_hoadDonNhaps(hoadDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.nhanVien = null;
		}
		
		private void attach_hoadDonXuats(hoadDonXuat entity)
		{
			this.SendPropertyChanging();
			entity.nhanVien = this;
		}
		
		private void detach_hoadDonXuats(hoadDonXuat entity)
		{
			this.SendPropertyChanging();
			entity.nhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhomSP")]
	public partial class nhomSP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maLoai;
		
		private string _tenLoai;
		
		private EntitySet<sanPham> _sanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLoaiChanging(string value);
    partial void OnmaLoaiChanged();
    partial void OntenLoaiChanging(string value);
    partial void OntenLoaiChanged();
    #endregion
		
		public nhomSP()
		{
			this._sanPhams = new EntitySet<sanPham>(new Action<sanPham>(this.attach_sanPhams), new Action<sanPham>(this.detach_sanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					this.OnmaLoaiChanging(value);
					this.SendPropertyChanging();
					this._maLoai = value;
					this.SendPropertyChanged("maLoai");
					this.OnmaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLoai", DbType="NVarChar(50)")]
		public string tenLoai
		{
			get
			{
				return this._tenLoai;
			}
			set
			{
				if ((this._tenLoai != value))
				{
					this.OntenLoaiChanging(value);
					this.SendPropertyChanging();
					this._tenLoai = value;
					this.SendPropertyChanged("tenLoai");
					this.OntenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhomSP_sanPham", Storage="_sanPhams", ThisKey="maLoai", OtherKey="maLoai")]
		public EntitySet<sanPham> sanPhams
		{
			get
			{
				return this._sanPhams;
			}
			set
			{
				this._sanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sanPhams(sanPham entity)
		{
			this.SendPropertyChanging();
			entity.nhomSP = this;
		}
		
		private void detach_sanPhams(sanPham entity)
		{
			this.SendPropertyChanging();
			entity.nhomSP = null;
		}
	}
	
	public partial class select_SPResult
	{
		
		private string _maSP;
		
		private string _tenSP;
		
		private System.Nullable<double> _gia;
		
		private System.Data.Linq.Binary _anh;
		
		private System.Nullable<int> _soLuong;
		
		private string _thongSo;
		
		private string _maLoai;
		
		private string _maLoai1;
		
		private string _tenLoai;
		
		public select_SPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maSP
		{
			get
			{
				return this._maSP;
			}
			set
			{
				if ((this._maSP != value))
				{
					this._maSP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenSP", DbType="NVarChar(50)")]
		public string tenSP
		{
			get
			{
				return this._tenSP;
			}
			set
			{
				if ((this._tenSP != value))
				{
					this._tenSP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Float")]
		public System.Nullable<double> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this._gia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anh", DbType="Image")]
		public System.Data.Linq.Binary anh
		{
			get
			{
				return this._anh;
			}
			set
			{
				if ((this._anh != value))
				{
					this._anh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this._soLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thongSo", DbType="NVarChar(50)")]
		public string thongSo
		{
			get
			{
				return this._thongSo;
			}
			set
			{
				if ((this._thongSo != value))
				{
					this._thongSo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", DbType="NVarChar(50)")]
		public string maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					this._maLoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maLoai1
		{
			get
			{
				return this._maLoai1;
			}
			set
			{
				if ((this._maLoai1 != value))
				{
					this._maLoai1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLoai", DbType="NVarChar(50)")]
		public string tenLoai
		{
			get
			{
				return this._tenLoai;
			}
			set
			{
				if ((this._tenLoai != value))
				{
					this._tenLoai = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
